// Localization translations for English, German, French, Dutch, Arabic, Chinese, and Spanish
const translations = {
  en: {
    caseTitle: "Scaling EV Charging Globally",
    caseBannerAlt: "EV Charging App",
    roleLabel: "My Role:",
    role: "Lead UI UX Designer",
    failedTitle: "What Failed?",
    barrierTitle: "The Barrier",
    barrierDesc: "Sintio started small, like a neighborhood charging buddy. Cute, useful... but stuck. The platform couldn’t scale, the design felt clunky, and users sighed more than they smiled. Users fumbled through charging sessions. Operators cursed messy charger management. Scaling to Europe or the USA? Forget it.",
    barrierHighlight: "The platform couldn’t scale, the design felt clunky,",
    ibmTitle: "IBM Enterprise Thinking",
    ibmDesc: "To break the deadlock, I leaned on IBM Enterprise Design Thinking. Why? Because it let me balance business constraints with real user needs—without letting either side dominate.",
    ibmImgAlt: "IBM Enterprise Design",
    visionTitle: "Setting the Vision",
    visionDesc: "I defined two core “Hills”:",
    hillScalability: "Scalability: Enable Sintio to become a white-label EV solution for businesses and organizations.",
    hillInvestor: "Investor Confidence: Redesign the experience to be clear, modern, and fundable.",
    hillSummary: "These Hills set the north star for all design decisions.",
    userFeedbackTitle: "Initial User Feedback (Old Portal)",
    userFeedbackDesc: "At the very start, I observed real users using the existing portal.",
    userFeedbackPain: "Identified pain points: confusing navigation, lack of flexibility, and poor usability.",
    userFeedbackBudget: "This gave me the baseline problems to address before budget constraints kicked in.",
    sponsorTitle: "Sponsor Users — Stakeholders & Investors",
    sponsorDesc: "At the very start, I observed real users using the existing portal.",
    sponsorPain: "Identified pain points: confusing navigation, lack of flexibility, and poor usability.",
    sponsorBudget: "This gave me the baseline problems to address before budget constraints kicked in.",
    playbacksTitle: "Playbacks — Iterative Collaboration",
    playbacksDesc: "IBM EDT emphasizes Playbacks: regular checkpoints for alignment.",
    playbacksSessions: "I ran playback sessions at every design milestone.",
    playbacksPrototypes: "Prototypes in Figma were tested, critiqued, and improved collaboratively.",
    playbacksSummary: "This kept design transparent, iterative, and collaborative.",
    iterationTitle: "Iteration & Design System",
    iterationDesc: "Developed a scalable design system for consistency and white-label adaptability.",
    iterationFlows: "Iterated on flows for charging, payments, and fleet management.",
    iterationCycles: "Each cycle simplified user journeys while ensuring business goals were met.",
    iterationSummary: "The system thinking approach ensured long-term scalability.",
    reintroduceTitle: "Reintroducing Real Users",
    reintroduceDesc: "Once funding was secured, I reintroduced real users into the process.",
    reintroduceInterviews: "Conducted contextual interviews with EV drivers and operators.",
    reintroduceObserve: "Observed them navigating the redesigned prototypes vs. the old portal.",
    reintroduceRefine: "Final refinements were made to ensure the design met real-world usability standards.",
    reintroduceSummary: "This bridged the gap between stakeholder-driven iterations and user-validated design.",
    reflectionTitle: "Reflection",
    reflectionDesc1: "This project taught me the importance of adapting design methods to reality. While I couldn’t always follow a textbook user-centered process, IBM Enterprise Design Thinking gave me the structure to balance business constraints, sponsor input, and real-user validation. In the end, the design was not only fundable but also usable — proving that even under pressure, UX thinking can deliver both business impact and human-centered value.",
  reflectionDesc2: "Leading Sintio’s redesign as a solo designer taught me how to merge strategy, design thinking, and execution into one seamless process. I wasn’t just creating screens — I was aligning stakeholders, shaping product vision, and enabling a $2M funding round through design alone. This case study reflects what I bring to any team: clarity, adaptability, and measurable impact through design.",
    home: "Home",
    about: "About me",
    contact: "Contact me",
    copyright: "© Code by Ishan",
    ev: "EV Multiplatform",
    hero_title: "Turning \u201dmeh\u201d products into Market Leaders",
    hero_para: "Users abandon confusing products in seconds. Make yours impossible to ignore — hire an accessibility-focused UI UX designer (WCAG).",
    explore_btn: "Explore my work",
    explore_btn_text: "Explore my work",
    hero_sub: "Crafting intuitive, human-first experiences inside complex systems.",
    badge_product: "Product Design",
    badge_ux: "UI Engineering",
    badge_ui: "UX Strategy",
    badge_design: "Design Systems",
    meh: "Meh",
    problem_stat: "88% of users abandon products due to poor user experience — poor UI UX turns potential market leaders into forgettable failures.",
    solution_title: "Here’s How I make Products Win",
    carousel_prev: "←",
    carousel_next: "→",
    story_title: "STORYTELLING FIRST",
    story_desc: "I design story-first interactions that guide people effortlessly across product, web, and mobile—building emotional resonance that lasts beyond the session. From journey mapping and microcopy to motion and component systems, your brand voice becomes tangible. Make your product memorable and conversion-ready — hire a brand experience designer for cross-platform products.",
    conversion_title: "CONVERSION FOCUSED",
    conversion_desc: "I design for outcomes, not aesthetics—choose a conversion-first UI UX design service to lift signups, activation, and revenue, with every decision measured against clear funnel metrics.",
    endtoend_title: "END TO END EXECUTION",
    endtoend_desc: "From research and strategy through design, development, and testing, I run the full product cycle to drive growth—an end-to-end UI UX design and development service focused on conversion, retention, and measurable impact.",
    know_about: "Know about me →",
    testimonial_label: "Client Testimonial",
    testimonial_title: "What They Say?",
    testimonial_1: "BNP didn't just help me write a book—they helped me find my voice. I've never felt more seen or more confident in my story.",
    testimonial_1_name: "Neha D.",
    testimonial_1_role: "Wellness Coach",
    testimonial_2: "From scattered notes to a professionally written book in 30 days. The team made the entire process smooth, sharp, and stress-free",
    testimonial_2_name: "Jay K.",
    testimonial_2_role: "Startup Founder",
    testimonial_3: "I never imagined I'd see my story in a book—let alone feel proud of it. I was overwhelmed, unsure, and had no idea where to begin. But British Noble Press listened to me, really listened, and turned my messy voice notes into something powerful and personal.",
    testimonial_3_name: "Fatima S.",
    testimonial_3_role: "Business Consultant, UAE",
    faq_title: "Frequently Asked Questions",
    faq_q1: "What exactly do you deliver, start to finish?",
    faq_a1: "I deliver an end-to-end UI UX research, design, front-end development, and testing service from discovery to launch. Hire a remote UI UX designer and front-end developer for a conversion-focused, measurable release.",
    faq_q2: "Can you help us launch fast from Figma?",
    faq_a2: "Yes—launch-ready Figma to Webflow or Framer implementation with pixel accuracy, CMS, and analytics. Book a conversion-first build that ships fast for teams in Europe, USA, Canada, Singapore, and Hong Kong.",
    faq_q3: "How do you improve conversion, activation, and retention?",
    faq_a3: "I run experiment-driven UI UX for conversion optimization across signup, onboarding, and paywall/checkout. Expect prioritized A/B tests and onboarding optimization to lift activation and reduce churn.",
    faq_q4: "Do you cover accessibility and performance?",
    faq_a4: "Yes—accessibility-first UI UX to meet WCAG AA with semantic structure, ARIA, and keyboard flows. I pair this with Core Web Vitals optimization for speed, SEO, and better mobile conversion.",
    faq_q5: "How do pricing and engagement models work?",
    faq_a5: "Choose fixed-scope productized design packages, a monthly design subscription, or a fractional product designer model. All options keep velocity high, costs predictable, and roadmaps outcome-driven.",
    faq_q6: "Which industries and regions do you work with?",
    faq_a6: "I partner with SaaS, e-commerce, fintech, healthcare, education, and internal tools. Hire a remote UI UX designer for global teams with time-zone friendly collaboration across Europe, USA, Canada, Singapore, and Hong Kong.",
    pricing_label: "Pricing",
    pricing_title: "Membership pricing",
    pricing_italic: "pricing",
    pricing_desc: "Invest in design that drives your business.<br>Clear, straightforward plans tailored to your needs.",
    pricing_standard: "Standard",
    pricing_standard_sub: "Transform your existing design into a conversion machine.",
    pricing_standard_price: "$849",
    pricing_standard_note: "One Time. 50% advance, 50% on delivery",
    pricing_standard_btn: "Subscribe today",
    pricing_standard_link: "Book a call",
    pricing_standard_f1: "Complete UX audit with actionable insights",
    pricing_standard_f2: "Strategic redesign of your existing interface",
    pricing_standard_f3: "Figma files with developer-ready specifications",
    pricing_standard_f4: "2-3 day delivery per request",
    pricing_standard_f5: "Up to 2 revisions per project",
    pricing_standard_f6: "Slack/Trello project management",
    pricing_standard_f7: "Pause or cancel anytime",
    pricing_standard_s1: "SaaS",
    pricing_standard_s2: "Redesign",
    pricing_standard_s3: "Optimization",
    pricing_pro: "Pro",
    pricing_popular: "Popular",
    pricing_pro_sub: "Build your brand from the ground up with cohesive, scalable design.",
    pricing_pro_price: "$1,449",
    pricing_pro_note: "One Time. 50% advance, 50% on delivery",
    pricing_pro_btn: "Subscribe today",
    pricing_pro_link: "Book a call",
    pricing_pro_f1: "Complete brand identity development",
    pricing_pro_f2: "Comprehensive design system creation",
    pricing_pro_f3: "UI/UX design for web and mobile",
    pricing_pro_f4: "Up to 4 revisions per project",
    pricing_pro_f5: "Priority 2-3 day turnaround",
    pricing_pro_f6: "Advanced prototyping and user flows",
    pricing_pro_f7: "Brand guidelines documentation",
    pricing_pro_s1: "Scaling",
    pricing_pro_s2: "Stand Out",
    pricing_pro_s3: "Branding",
    pricing_project: "Project-Based",
    pricing_project_sub: "Custom design and development for your unique vision.",
    pricing_project_price: "from $2,499",
    pricing_project_note: "One Time. 50% advance, 50% on delivery",
    pricing_project_btn: "Request quote",
    pricing_project_link: "Book a call",
    pricing_project_f1: "Custom project scope and timeline",
    pricing_project_f2: "Complete brand and UI/UX design",
    pricing_project_f3: "Frontend development and implementation",
    pricing_project_f4: "Responsive, performance-optimized code",
    pricing_project_f5: "Unlimited revisions during development",
    pricing_project_f6: "Quality assurance and testing",
    pricing_project_f7: "3 months post-launch support",
    pricing_project_s1: "Designing",
    pricing_project_s2: "Development",
    pricing_project_s3: "Launch",
    costs: "costs you more than you think",
    work: "Work"
  },
  de: {
  caseTitle: "EV-Laden weltweit skalieren",
  caseBannerAlt: "EV-Lade-App",
  roleLabel: "Meine Rolle:",
  role: "Lead UI UX Designer",
  failedTitle: "Was ist gescheitert?",
  barrierTitle: "Die Barriere",
  barrierDesc: "Sintio begann klein, wie ein Nachbarschafts-Ladefreund. Nützlich, aber festgefahren. Die Plattform konnte nicht skalieren, das Design war sperrig, und die Nutzer waren frustriert. Nutzer stolperten durch Ladevorgänge. Betreiber fluchten über das Management. Skalierung nach Europa oder USA? Vergiss es.",
  barrierHighlight: "Die Plattform konnte nicht skalieren, das Design war sperrig,",
  ibmTitle: "IBM Enterprise Thinking",
  ibmDesc: "Um die Blockade zu lösen, setzte ich auf IBM Enterprise Design Thinking. Es half, Geschäftsanforderungen und Nutzerbedürfnisse auszubalancieren.",
  ibmImgAlt: "IBM Enterprise Design",
  visionTitle: "Vision setzen",
  visionDesc: "Ich definierte zwei Kern-Hills:",
  hillScalability: "Skalierbarkeit: Sintio als White-Label-EV-Lösung für Unternehmen.",
  hillInvestor: "Investorenvertrauen: Klare, moderne und förderfähige Erfahrung.",
  hillSummary: "Diese Hills waren der Nordstern für alle Designentscheidungen.",
  userFeedbackTitle: "Erstes Nutzerfeedback (altes Portal)",
  userFeedbackDesc: "Zu Beginn beobachtete ich echte Nutzer im Portal.",
  userFeedbackPain: "Schmerzpunkte: Verwirrende Navigation, wenig Flexibilität, schlechte Usability.",
  userFeedbackBudget: "Das waren die Basisprobleme vor Budgetgrenzen.",
  sponsorTitle: "Sponsor-Nutzer — Stakeholder & Investoren",
  sponsorDesc: "Zu Beginn beobachtete ich echte Nutzer im Portal.",
  sponsorPain: "Schmerzpunkte: Verwirrende Navigation, wenig Flexibilität, schlechte Usability.",
  sponsorBudget: "Das waren die Basisprobleme vor Budgetgrenzen.",
  playbacksTitle: "Playbacks — Iterative Zusammenarbeit",
  playbacksDesc: "IBM EDT setzt auf Playbacks: regelmäßige Abstimmungen.",
  playbacksSessions: "Playbacks bei jedem Design-Meilenstein.",
  playbacksPrototypes: "Figma-Prototypen wurden getestet und gemeinsam verbessert.",
  playbacksSummary: "Das hielt das Design transparent und kollaborativ.",
  iterationTitle: "Iteration & Designsystem",
  iterationDesc: "Skalierbares Designsystem für Konsistenz und White-Label-Fähigkeit.",
  iterationFlows: "Iterationen für Laden, Zahlung, Flottenmanagement.",
  iterationCycles: "Jede Runde vereinfachte die Nutzerreise und erfüllte Geschäftsziele.",
  iterationSummary: "Systemdenken sicherte Skalierbarkeit.",
  reintroduceTitle: "Echte Nutzer wieder einbeziehen",
  reintroduceDesc: "Nach Finanzierung holte ich echte Nutzer zurück.",
  reintroduceInterviews: "Kontextinterviews mit EV-Fahrern und Betreibern.",
  reintroduceObserve: "Beobachtung im neuen vs. alten Portal.",
  reintroduceRefine: "Letzte Anpassungen für echte Usability.",
  reintroduceSummary: "So wurde Stakeholder-Iteration mit Nutzer-Validierung verbunden.",
  reflectionTitle: "Reflexion",
  reflectionDesc1: "Das Projekt zeigte, wie wichtig flexible Methoden sind. IBM EDT half, Business, Stakeholder und Nutzer auszubalancieren. Am Ende war das Design förderfähig und nutzbar — UX kann auch unter Druck Wirkung zeigen.",
  reflectionDesc2: "Als Solodesigner habe ich Strategie, Design und Umsetzung vereint. Ich habe nicht nur Screens gebaut, sondern Stakeholder ausgerichtet, Vision geformt und $2M Funding ermöglicht. Das bringe ich in jedes Team: Klarheit, Anpassungsfähigkeit, messbare Wirkung.",
    home: "Startseite",
    about: "Über mich",
    contact: "Kontakt",
    copyright: "© Code von Ishan",
    ev: "EV Multiplattform",
    hero_title: "Verwandlung von \u201dmeh\u201d Produkten in Marktführer",
    hero_para: "Nutzer wenden verwirrende Produkte in Sekunden ab. Machen Sie Ihre Produkte unmöglich zu ignorieren - engagieren Sie einen auf Barrierefreiheit fokussierten UI UX Designer (WCAG).",
    explore_btn: "Entdecken Sie meine Arbeit",
    explore_btn_text: "Entdecken Sie meine Arbeit",
    hero_sub: "Gestaltung intuitiver, menschlicher Erfahrungen in komplexen Systemen.",
    badge_product: "Produktdesign",
    badge_ux: "UI-Entwicklung",
    badge_ui: "UX-Strategie",
    badge_design: "Designsysteme",
    meh: "Meh",
    problem_stat: "88% der Nutzer wenden Produkte aufgrund schlechter Benutzererfahrung ab - schlechtes UI UX verwandelt potenzielle Marktführer in vergessene Misserfolge.",
    solution_title: "So lasse ich Produkte gewinnen",
    carousel_prev: "←",
    carousel_next: "→",
    story_title: "ERZÄHLENDE GESTALTUNG ZUERST",
    story_desc: "Ich gestalte erzählerische Interaktionen, die Menschen mühelos über Produkt, Web und Mobil führen - und dabei emotionale Resonanz aufbauen, die über die Sitzung hinaus anhält. Von der Reiseplanung und Mikrocopy bis hin zu Bewegung und Komponenten-Systemen wird Ihre Markenstimme greifbar. Machen Sie Ihr Produkt unvergesslich und konversionsbereit - engagieren Sie einen Designer für Markenerlebnisse für plattformübergreifende Produkte.",
    conversion_title: "KONVERSION IM FOKUS",
    conversion_desc: "Ich gestalte nach Ergebnissen, nicht nach Ästhetik - wählen Sie einen konversionsorientierten UI UX Designservice, um Anmeldungen, Aktivierung und Umsatz zu steigern, wobei jede Entscheidung anhand klarer Trichtermetriken gemessen wird.",
    endtoend_title: "ENDE-zu-ENDE-AUSFÜHRUNG",
    endtoend_desc: "Von der Forschung und Strategie über Design, Entwicklung und Test bis hin zur vollständigen Produktzyklenführung zur Wachstumssteigerung - ein End-to-End UI UX Design- und Entwicklungsservice, der sich auf Konversion, Bindung und messbare Auswirkungen konzentriert.",
    know_about: "Erfahren Sie mehr über mich →",
    testimonial_label: "Kundenreferenz",
    testimonial_title: "Was sie sagen?",
    testimonial_1: "BNP hat mir nicht nur geholfen, ein Buch zu schreiben - sie haben mir geholfen, meine Stimme zu finden. Ich habe mich noch nie so gesehen oder so sicher in meiner Geschichte gefühlt.",
    testimonial_1_name: "Neha D.",
    testimonial_1_role: "Wellness-Coach",
    testimonial_2: "Von verstreuten Notizen zu einem professionell geschriebenen Buch in 30 Tagen. Das Team hat den gesamten Prozess reibungslos, präzise und stressfrei gestaltet.",
    testimonial_2_name: "Jay K.",
    testimonial_2_role: "Startup-Gründer",
    testimonial_3: "Ich hätte nie gedacht, dass ich meine Geschichte in einem Buch sehen würde - geschweige denn stolz darauf sein könnte. Ich war überwältigt, unsicher und hatte keine Ahnung, wo ich anfangen sollte. Aber British Noble Press hat mir zugehört, wirklich zugehört, und meine chaotischen Sprachnotizen in etwas Kraftvolles und Persönliches verwandelt.",
    testimonial_3_name: "Fatima S.",
    testimonial_3_role: "Business Consultant, VAE",
    faq_title: "Häufig gestellte Fragen",
    faq_q1: "Was genau liefern Sie von Anfang bis Ende?",
    faq_a1: "Ich liefere einen End-to-End UI UX Forschungs-, Design-, Front-End Entwicklungs- und Testservice von der Entdeckung bis zur Markteinführung. Engagieren Sie einen Remote UI UX Designer und Front-End Entwickler für eine konversionsorientierte, messbare Veröffentlichung.",
    faq_q2: "Können Sie uns helfen, schnell von Figma aus zu starten?",
    faq_a2: "Ja - startbereite Figma zu Webflow oder Framer Implementierung mit pixelgenauer Genauigkeit, CMS und Analytik. Buchen Sie einen konversionsorientierten Build, der schnell für Teams in Europa, den USA, Kanada, Singapur und Hongkong versendet wird.",
    faq_q3: "Wie verbessern Sie die Konversion, Aktivierung und Bindung?",
    faq_a3: "Ich führe experimentell gesteuertes UI UX zur Optimierung der Konversion über Anmeldung, Onboarding und Paywall/Checkout durch. Erwarten Sie priorisierte A/B-Tests und Onboarding-Optimierungen zur Steigerung der Aktivierung und Reduzierung der Abwanderung.",
    faq_q4: "Decken Sie Barrierefreiheit und Leistung ab?",
    faq_a4: "Ja - barrierefrei gestaltetes UI UX zur Erfüllung der WCAG AA mit semantischer Struktur, ARIA und Tastaturflüssen. Ich kombiniere dies mit der Optimierung der Core Web Vitals für Geschwindigkeit, SEO und bessere mobile Konversion.",
    faq_q5: "Wie funktionieren Preis- und Engagementmodelle?",
    faq_a5: "Wählen Sie festgelegte, produktisierte Designpakete, ein monatliches Designabonnement oder ein Modell für einen fractional Produktdesigner. Alle Optionen halten die Geschwindigkeit hoch, die Kosten vorhersehbar und die Fahrpläne ergebnisorientiert.",
    faq_q6: "Mit welchen Branchen und Regionen arbeiten Sie zusammen?",
    faq_a6: "Ich arbeite mit SaaS, E-Commerce, Fintech, Gesundheitswesen, Bildung und internen Tools zusammen. Engagieren Sie einen Remote UI UX Designer für globale Teams mit zeitzonenfreundlicher Zusammenarbeit in Europa, den USA, Kanada, Singapur und Hongkong.",
    pricing_label: "Preise",
    pricing_title: "Mitgliedschaftspreise",
    pricing_italic: "Preise",
    pricing_desc: "Investieren Sie in Design, das Ihr Geschäft vorantreibt.<br>Klare, unkomplizierte Pläne, die auf Ihre Bedürfnisse zugeschnitten sind.",
    pricing_standard: "Standard",
    pricing_standard_sub: "Verwandeln Sie Ihr bestehendes Design in eine Konversionsmaschine.",
    pricing_standard_price: "$849",
    pricing_standard_note: "Einmalig. 50% im Voraus, 50% bei Lieferung",
    pricing_standard_btn: "Jetzt abonnieren",
    pricing_standard_link: "Vereinbaren Sie einen Termin",
    pricing_standard_f1: "Umfassendes UX-Audit mit umsetzbaren Erkenntnissen",
    pricing_standard_f2: "Strategische Neugestaltung Ihrer bestehenden Benutzeroberfläche",
    pricing_standard_f3: "Figma-Dateien mit entwicklerbereiten Spezifikationen",
    pricing_standard_f4: "Lieferung in 2-3 Tagen pro Anfrage",
    pricing_standard_f5: "Bis zu 2 Überarbeitungen pro Projekt",
    pricing_standard_f6: "Projektmanagement über Slack/Trello",
    pricing_standard_f7: "Jederzeit pausieren oder kündigen",
    pricing_standard_s1: "SaaS",
    pricing_standard_s2: "Neugestaltung",
    pricing_standard_s3: "Optimierung",
    pricing_pro: "Pro",
    pricing_popular: "Beliebt",
    pricing_pro_sub: "Bauen Sie Ihre Marke von Grund auf mit kohärentem, skalierbarem Design.",
    pricing_pro_price: "$1,449",
    pricing_pro_note: "Einmalig. 50% im Voraus, 50% bei Lieferung",
    pricing_pro_btn: "Jetzt abonnieren",
    pricing_pro_link: "Vereinbaren Sie einen Termin",
    pricing_pro_f1: "Umfassende Entwicklung der Markenidentität",
    pricing_pro_f2: "Umfassende Erstellung des Design Systems",
    pricing_pro_f3: "UI/UX Design für Web und Mobil",
    pricing_pro_f4: "Bis zu 4 Überarbeitungen pro Projekt",
    pricing_pro_f5: "Priorisierte 2-3 Tage Bearbeitungszeit",
    pricing_pro_f6: "Erweiterte Prototypenerstellung und Benutzerflüsse",
    pricing_pro_f7: "Dokumentation der Markenrichtlinien",
    pricing_pro_s1: "Skalierung",
    pricing_pro_s2: "Hervorstechen",
    pricing_pro_s3: "Markenbildung",
    pricing_project: "Projektbasiert",
    pricing_project_sub: "Maßgeschneidertes Design und Entwicklung für Ihre einzigartige Vision.",
    pricing_project_price: "ab $2,499",
    pricing_project_note: "Einmalig. 50% im Voraus, 50% bei Lieferung",
    pricing_project_btn: "Angebot anfordern",
    pricing_project_link: "Vereinbaren Sie einen Termin",
    pricing_project_f1: "Maßgeschneiderter Projektumfang und Zeitplan",
    pricing_project_f2: "Komplettes Marken- und UI/UX-Design",
    pricing_project_f3: "Frontend-Entwicklung und Implementierung",
    pricing_project_f4: "Responsiver, leistungsoptimierter Code",
    pricing_project_f5: "Unbegrenzte Überarbeitungen während der Entwicklung",
    pricing_project_f6: "Qualitätssicherung und Test",
    pricing_project_f7: "3 Monate Unterstützung nach dem Start",
    pricing_project_s1: "Design",
    pricing_project_s2: "Entwicklung",
    pricing_project_s3: "Start",
    costs: "kostet Sie mehr als Sie denken",
    work: "Arbeit"
  },
  fr: {
  caseTitle: "Déployer la recharge EV à l'échelle mondiale",
  caseBannerAlt: "Application de recharge EV",
  roleLabel: "Mon rôle :",
  role: "Lead UI UX Designer",
  failedTitle: "Qu'est-ce qui a échoué ?",
  barrierTitle: "La barrière",
  barrierDesc: "Sintio a commencé petit, comme un compagnon de recharge de quartier. Utile, mais limité. La plateforme ne pouvait pas évoluer, le design était maladroit, et les utilisateurs étaient frustrés. Navigation difficile, gestion complexe. S'étendre en Europe ou aux USA ? Impossible.",
  barrierHighlight: "La plateforme ne pouvait pas évoluer, le design était maladroit,",
  ibmTitle: "IBM Enterprise Thinking",
  ibmDesc: "Pour débloquer la situation, j'ai utilisé IBM Enterprise Design Thinking. Cela m'a permis d'équilibrer contraintes business et besoins utilisateurs.",
  ibmImgAlt: "Design d'entreprise IBM",
  visionTitle: "Définir la vision",
  visionDesc: "J'ai défini deux “Hills” clés :",
  hillScalability: "Scalabilité : Permettre à Sintio de devenir une solution EV en marque blanche.",
  hillInvestor: "Confiance des investisseurs : Expérience claire, moderne et finançable.",
  hillSummary: "Ces Hills ont guidé toutes les décisions de design.",
  userFeedbackTitle: "Retour utilisateur initial (ancien portail)",
  userFeedbackDesc: "J'ai observé de vrais utilisateurs sur l'ancien portail.",
  userFeedbackPain: "Points de douleur : navigation confuse, manque de flexibilité, mauvaise utilisabilité.",
  userFeedbackBudget: "Cela a donné la base avant les contraintes budgétaires.",
  sponsorTitle: "Utilisateurs sponsors — Parties prenantes & investisseurs",
  sponsorDesc: "J'ai observé de vrais utilisateurs sur l'ancien portail.",
  sponsorPain: "Points de douleur : navigation confuse, manque de flexibilité, mauvaise utilisabilité.",
  sponsorBudget: "Cela a donné la base avant les contraintes budgétaires.",
  playbacksTitle: "Playbacks — Collaboration itérative",
  playbacksDesc: "IBM EDT met l'accent sur les playbacks : points de contrôle réguliers.",
  playbacksSessions: "Playbacks à chaque étape clé.",
  playbacksPrototypes: "Prototypes Figma testés et améliorés en équipe.",
  playbacksSummary: "Design transparent, itératif et collaboratif.",
  iterationTitle: "Itération & Design System",
  iterationDesc: "Système de design évolutif pour cohérence et adaptabilité.",
  iterationFlows: "Itérations sur les flux de recharge, paiement, gestion de flotte.",
  iterationCycles: "Chaque cycle a simplifié le parcours utilisateur et atteint les objectifs business.",
  iterationSummary: "La pensée système a assuré la scalabilité.",
  reintroduceTitle: "Réintégrer de vrais utilisateurs",
  reintroduceDesc: "Une fois le financement obtenu, j'ai réintégré de vrais utilisateurs.",
  reintroduceInterviews: "Entretiens contextuels avec conducteurs et opérateurs EV.",
  reintroduceObserve: "Observation sur prototypes vs ancien portail.",
  reintroduceRefine: "Derniers ajustements pour une vraie utilisabilité.",
  reintroduceSummary: "Pont entre itérations sponsor et validation utilisateur.",
  reflectionTitle: "Réflexion",
  reflectionDesc1: "Ce projet m'a appris à adapter les méthodes de design à la réalité. IBM EDT m'a donné la structure pour équilibrer business, sponsors et validation utilisateur. Au final, le design était finançable et utilisable — la pensée UX peut avoir un impact même sous pression.",
  reflectionDesc2: "En solo, j'ai fusionné stratégie, design et exécution. J'ai aligné les parties prenantes, défini la vision produit et permis un financement de $2M. Ce cas montre ce que j'apporte : clarté, adaptabilité, impact mesurable.",
    home: "Accueil",
    about: "À propos de moi",
    contact: "Contactez-moi",
    copyright: "© Code par Ishan",
    ev: "EV Multiplateforme",
    hero_title: "Transformer les produits \u201dmeh\u201d en leaders du marché",
    hero_para: "Les utilisateurs abandonnent les produits confus en quelques secondes. Rendez les vôtres impossibles à ignorer : engagez un designer UI UX axé sur l'accessibilité (WCAG).",
    explore_btn: "Découvrez mon travail",
    explore_btn_text: "Découvrez mon travail",
    hero_sub: "Création d'expériences intuitives et centrées sur l'humain au sein de systèmes complexes.",
    badge_product: "Design de produit",
    badge_ux: "Ingénierie UI",
    badge_ui: "Stratégie UX",
    badge_design: "Systèmes de design",
    meh: "Meh",
    problem_stat: "88% des utilisateurs abandonnent les produits en raison d'une mauvaise expérience utilisateur - un mauvais UI UX transforme les leaders potentiels du marché en échecs oubliables.",
    solution_title: "Voici comment je fais gagner des produits",
    carousel_prev: "←",
    carousel_next: "→",
    story_title: "RACONTER D'ABORD",
    story_desc: "Je conçois des interactions axées sur l'histoire qui guident les gens sans effort à travers le produit, le web et le mobile, créant ainsi une résonance émotionnelle qui dure au-delà de la session. De la cartographie du parcours et du microcontenu aux systèmes de mouvement et de composants, la voix de votre marque devient tangible. Rendez votre produit mémorable et prêt à la conversion : engagez un designer d'expérience de marque pour des produits multiplateformes.",
    conversion_title: "AXÉ SUR LA CONVERSION",
    conversion_desc: "Je conçois pour des résultats, pas pour l'esthétique - choisissez un service de design UI UX axé sur la conversion pour augmenter les inscriptions, l'activation et les revenus, chaque décision étant mesurée par rapport à des indicateurs clairs du tunnel de conversion.",
    endtoend_title: "EXÉCUTION DE A À Z",
    endtoend_desc: "De la recherche et de la stratégie à la conception, au développement et aux tests, je gère l'ensemble du cycle de vie du produit pour stimuler la croissance - un service de design et de développement UI UX de bout en bout axé sur la conversion, la rétention et l'impact mesurable.",
    know_about: "En savoir plus sur moi →",
    testimonial_label: "Témoignage client",
    testimonial_title: "Ce qu'ils disent ?",
    testimonial_1: "BNP ne m'a pas seulement aidé à écrire un livre - ils m'ont aidé à trouver ma voix. Je ne me suis jamais senti aussi vu ou aussi confiant dans mon histoire.",
    testimonial_1_name: "Neha D.",
    testimonial_1_role: "Coach bien-être",
    testimonial_2: "D'notes éparses à un livre professionnellement écrit en 30 jours. L'équipe a rendu l'ensemble du processus fluide, précis et sans stress",
    testimonial_2_name: "Jay K.",
    testimonial_2_role: "Fondateur de startup",
    testimonial_3: "Je n'aurais jamais imaginé voir mon histoire dans un livre - encore moins en être fier. J'étais submergé, incertain, et je n'avais aucune idée de par où commencer. Mais British Noble Press m'a écouté, a vraiment écouté, et a transformé mes notes vocales désordonnées en quelque chose de puissant et de personnel.",
    testimonial_3_name: "Fatima S.",
    testimonial_3_role: "Consultante en affaires, Émirats Arabes Unis",
    faq_title: "Questions Fréquemment Posées",
    faq_q1: "Que livrez-vous exactement, de A à Z ?",
    faq_a1: "Je livre un service complet de recherche, de design, de développement front-end et de test UI UX de la découverte à la mise en ligne. Engagez un designer UI UX à distance et un développeur front-end pour une publication axée sur la conversion et mesurable.",
    faq_q2: "Pouvez-vous nous aider à lancer rapidement depuis Figma ?",
    faq_a2: "Oui - mise en œuvre prête à l'emploi de Figma à Webflow ou Framer avec une précision pixel, CMS et analyses. Réservez une construction axée sur la conversion qui se déploie rapidement pour des équipes en Europe, aux États-Unis, au Canada, à Singapour et à Hong Kong.",
    faq_q3: "Comment améliorez-vous la conversion, l'activation et la rétention ?",
    faq_a3: "Je fais de l'UI UX pilotée par des expériences pour l'optimisation de la conversion à travers l'inscription, l'intégration et le mur de paiement/le paiement. Attendez-vous à des tests A/B et à une optimisation de l'intégration priorisés pour augmenter l'activation et réduire le taux de désabonnement.",
    faq_q4: "Couvrez-vous l'accessibilité et la performance ?",
    faq_a4: "Oui - UI UX axé sur l'accessibilité pour répondre aux normes WCAG AA avec une structure sémantique, ARIA et des flux clavier. J'associe cela à l'optimisation des Core Web Vitals pour la vitesse, le SEO et une meilleure conversion mobile.",
    faq_q5: "Comment fonctionnent les modèles de prix et d'engagement ?",
    faq_a5: "Choisissez parmi des packages de design productisés à portée fixe, un abonnement de design mensuel ou un modèle de designer produit fractionné. Toutes les options maintiennent une vitesse élevée, des coûts prévisibles et des feuilles de route axées sur les résultats.",
    faq_q6: "Avec quelles industries et régions travaillez-vous ?",
    faq_a6: "Je collabore avec des entreprises SaaS, de e-commerce, fintech, santé, éducation et outils internes. Engagez un designer UI UX à distance pour des équipes globales avec une collaboration adaptée aux fuseaux horaires en Europe, aux États-Unis, au Canada, à Singapour et à Hong Kong.",
    pricing_label: "Tarification",
    pricing_title: "Tarification par adhésion",
    pricing_italic: "tarification",
    pricing_desc: "Investissez dans un design qui propulse votre entreprise.<br>Des plans clairs et simples adaptés à vos besoins.",
    pricing_standard: "Standard",
    pricing_standard_sub: "Transformez votre design existant en une machine à conversion.",
    pricing_standard_price: "$849",
    pricing_standard_note: "Une fois. 50% d'avance, 50% à la livraison",
    pricing_standard_btn: "Abonnez-vous dès aujourd'hui",
    pricing_standard_link: "Réservez un appel",
    pricing_standard_f1: "Audit UX complet avec des insights exploitables",
    pricing_standard_f2: "Refonte stratégique de votre interface existante",
    pricing_standard_f3: "Fichiers Figma avec spécifications prêtes pour les développeurs",
    pricing_standard_f4: "Livraison en 2-3 jours par demande",
    pricing_standard_f5: "Jusqu'à 2 révisions par projet",
    pricing_standard_f6: "Gestion de projet Slack/Trello",
    pricing_standard_f7: "Mettez en pause ou annulez à tout moment",
    pricing_standard_s1: "SaaS",
    pricing_standard_s2: "Refonte",
    pricing_standard_s3: "Optimisation",
    pricing_pro: "Pro",
    pricing_popular: "Populaire",
    pricing_pro_sub: "Construisez votre marque de A à Z avec un design cohérent et évolutif.",
    pricing_pro_price: "$1,449",
    pricing_pro_note: "Une fois. 50% d'avance, 50% à la livraison",
    pricing_pro_btn: "Abonnez-vous dès aujourd'hui",
    pricing_pro_link: "Réservez un appel",
    pricing_pro_f1: "Développement complet de l'identité de marque",
    pricing_pro_f2: "Création complète du système de design",
    pricing_pro_f3: "Design UI/UX pour le web et le mobile",
    pricing_pro_f4: "Jusqu'à 4 révisions par projet",
    pricing_pro_f5: "Délai de traitement prioritaire de 2-3 jours",
    pricing_pro_f6: "Prototypage avancé et flux utilisateurs",
    pricing_pro_f7: "Documentation des directives de marque",
    pricing_pro_s1: "Évoluer",
    pricing_pro_s2: "Se démarquer",
    pricing_pro_s3: "Branding",
    pricing_project: "Basé sur le projet",
    pricing_project_sub: "Design et développement sur mesure pour votre vision unique.",
    pricing_project_price: "à partir de $2,499",
    pricing_project_note: "Une fois. 50% d'avance, 50% à la livraison",
    pricing_project_btn: "Demander un devis",
    pricing_project_link: "Réservez un appel",
    pricing_project_f1: "Portée et calendrier du projet sur mesure",
    pricing_project_f2: "Design complet de la marque et UI/UX",
    pricing_project_f3: "Développement front-end et implémentation",
    pricing_project_f4: "Code responsive et optimisé pour la performance",
    pricing_project_f5: "Révisions illimitées pendant le développement",
    pricing_project_f6: "Assurance qualité et tests",
    pricing_project_f7: "3 mois de support après le lancement",
    pricing_project_s1: "Conception",
    pricing_project_s2: "Développement",
    pricing_project_s3: "Lancement",
    costs: "coûte plus cher que vous ne le pensez",
    work: "Travail"
  },
  nl: {
  caseTitle: "EV-laden wereldwijd opschalen",
  caseBannerAlt: "EV-laadapp",
  roleLabel: "Mijn rol:",
  role: "Lead UI UX Designer",
  failedTitle: "Wat ging mis?",
  barrierTitle: "De barrière",
  barrierDesc: "Sintio begon klein, als een buurt-laadmaatje. Handig, maar vastgelopen. Het platform kon niet opschalen, het ontwerp was onhandig, en gebruikers waren gefrustreerd. Navigatie was lastig, beheer chaotisch. Opschalen naar Europa of de VS? Vergeet het.",
  barrierHighlight: "Het platform kon niet opschalen, het ontwerp was onhandig,",
  ibmTitle: "IBM Enterprise Thinking",
  ibmDesc: "Om de impasse te doorbreken, gebruikte ik IBM Enterprise Design Thinking. Dit hielp om zakelijke eisen en gebruikersbehoeften te balanceren.",
  ibmImgAlt: "IBM Enterprise Design",
  visionTitle: "De visie bepalen",
  visionDesc: "Ik definieerde twee kernpunten:",
  hillScalability: "Schaalbaarheid: Sintio als white-label EV-oplossing voor bedrijven.",
  hillInvestor: "Investeerdersvertrouwen: Duidelijke, moderne en financierbare ervaring.",
  hillSummary: "Deze punten waren het kompas voor alle ontwerpbeslissingen.",
  userFeedbackTitle: "Eerste gebruikersfeedback (oud portaal)",
  userFeedbackDesc: "Aan het begin observeerde ik echte gebruikers in het portaal.",
  userFeedbackPain: "Pijnpunten: verwarrende navigatie, weinig flexibiliteit, slechte bruikbaarheid.",
  userFeedbackBudget: "Dit gaf de basisproblemen vóór budgetbeperkingen.",
  sponsorTitle: "Sponsor-gebruikers — Stakeholders & investeerders",
  sponsorDesc: "Aan het begin observeerde ik echte gebruikers in het portaal.",
  sponsorPain: "Pijnpunten: verwarrende navigatie, weinig flexibiliteit, slechte bruikbaarheid.",
  sponsorBudget: "Dit gaf de basisproblemen vóór budgetbeperkingen.",
  playbacksTitle: "Playbacks — Iteratieve samenwerking",
  playbacksDesc: "IBM EDT legt nadruk op playbacks: regelmatige afstemming.",
  playbacksSessions: "Playbacks bij elke ontwerp-mijlpaal.",
  playbacksPrototypes: "Figma-prototypes getest en samen verbeterd.",
  playbacksSummary: "Dit hield het ontwerp transparant en samenwerkend.",
  iterationTitle: "Iteratie & Design System",
  iterationDesc: "Schaalbaar designsysteem voor consistentie en white-label aanpasbaarheid.",
  iterationFlows: "Iteraties voor laden, betalingen, vlootbeheer.",
  iterationCycles: "Elke cyclus vereenvoudigde gebruikersroutes en bereikte zakelijke doelen.",
  iterationSummary: "Systeemdenken zorgde voor schaalbaarheid.",
  reintroduceTitle: "Echte gebruikers opnieuw introduceren",
  reintroduceDesc: "Na financiering bracht ik echte gebruikers terug.",
  reintroduceInterviews: "Contextuele interviews met EV-rijders en operators.",
  reintroduceObserve: "Observatie in nieuwe vs. oude portaal.",
  reintroduceRefine: "Laatste verfijningen voor echte bruikbaarheid.",
  reintroduceSummary: "Zo werd stakeholder-iteratie met gebruikersvalidatie verbonden.",
  reflectionTitle: "Reflectie",
  reflectionDesc1: "Dit project liet zien hoe belangrijk het is om ontwerp-methoden aan te passen. IBM EDT gaf structuur om business, stakeholders en gebruikers te balanceren. Uiteindelijk was het ontwerp financierbaar en bruikbaar — UX kan ook onder druk impact maken.",
  reflectionDesc2: "Als solodesigner heb ik strategie, ontwerp en uitvoering samengebracht. Ik bouwde niet alleen schermen, maar bracht stakeholders op één lijn, vormde visie en maakte $2M funding mogelijk. Dat breng ik in elk team: helderheid, flexibiliteit, meetbare impact.",
    home: "Home",
    about: "Over mij",
    contact: "Contact",
    copyright: "© Code door Ishan",
    ev: "EV Multiplatform",
    hero_title: "Van \u201dmeh\u201d producten marktleiders maken",
    hero_para: "Gebruikers verlaten verwarrende producten in seconden. Zorg dat die van jou onmogelijk te negeren zijn - huur een op toegankelijkheid gerichte UI UX ontwerper (WCAG) in.",
    explore_btn: "Ontdek mijn werk",
    explore_btn_text: "Ontdek mijn werk",
    hero_sub: "Intuïtieve, mensgerichte ervaringen creëren binnen complexe systemen.",
    badge_product: "Productontwerp",
    badge_ux: "UI Engineering",
    badge_ui: "UX Strategie",
    badge_design: "Ontwerp systemen",
    meh: "Meh",
    problem_stat: "88% van de gebruikers verlaat producten vanwege een slechte gebruikerservaring - slechte UI UX verandert potentiële marktleiders in vergeten mislukkingen.",
    solution_title: "Zo laat ik producten winnen",
    carousel_prev: "←",
    carousel_next: "→",
    story_title: "VERHAALGERICHT ONTWERP",
    story_desc: "Ik ontwerp verhaalgerichte interacties die mensen moeiteloos begeleiden over product, web en mobiel - en emotionele resonantie opbouwen die verder gaat dan de sessie. Van het in kaart brengen van de reis en microcopy tot beweging en componentensystemen, jouw merkstem wordt tastbaar. Maak je product onvergetelijk en conversie-klaar - huur een merkervaring ontwerper in voor cross-platform producten.",
    conversion_title: "CONVERSIEGERICHT",
    conversion_desc: "Ik ontwerp voor resultaten, niet voor esthetiek - kies een conversie-eerste UI UX ontwerpdienst om aanmeldingen, activatie en omzet te verhogen, waarbij elke beslissing wordt gemeten aan de hand van duidelijke trechtermetriek.",
    endtoend_title: "EIND TOT EIND UITVOERING",
    endtoend_desc: "Van onderzoek en strategie tot ontwerp, ontwikkeling en testen, ik beheer de volledige productcyclus om groei te stimuleren - een end-to-end UI UX ontwerp en ontwikkelingsdienst gericht op conversie, retentie en meetbare impact.",
    know_about: "Leer meer over mij →",
    testimonial_label: "Klantgetuigenis",
    testimonial_title: "Wat ze zeggen?",
    testimonial_1: "BNP heeft me niet alleen geholpen om een boek te schrijven - ze hebben me geholpen mijn stem te vinden. Ik heb me nog nooit zo gezien of zo zelfverzekerd gevoeld in mijn verhaal.",
    testimonial_1_name: "Neha D.",
    testimonial_1_role: "Wellness Coach",
    testimonial_2: "Van verspreide notities naar een professioneel geschreven boek in 30 dagen. Het team maakte het hele proces soepel, scherp en stressvrij",
    testimonial_2_name: "Jay K.",
    testimonial_2_role: "Startup Founder",
    testimonial_3: "Ik had nooit gedacht dat ik mijn verhaal in een boek zou zien - laat staan er trots op zou zijn. Ik was overweldigd, onzeker, en had geen idee waar te beginnen. Maar British Noble Press luisterde naar me, luisterde echt, en veranderde mijn rommelige spraaknotities in iets krachtigs en persoonlijks.",
    testimonial_3_name: "Fatima S.",
    testimonial_3_role: "Business Consultant, VAE",
    faq_title: "Veelgestelde Vragen",
    faq_q1: "Wat levert u precies, van begin tot eind?",
    faq_a1: "Ik lever een end-to-end UI UX onderzoek, ontwerp, front-end ontwikkeling en testservice van ontdekking tot lancering. Huur een remote UI UX ontwerper en front-end ontwikkelaar in voor een conversiegerichte, meetbare release.",
    faq_q2: "Kun je ons snel helpen lanceren vanuit Figma?",
    faq_a2: "Ja - lanceerklare Figma naar Webflow of Framer implementatie met pixelprecisie, CMS en analytics. Boek een conversiegerichte build die snel verzendt voor teams in Europa, de VS, Canada, Singapore en Hong Kong.",
    faq_q3: "Hoe verbeter je conversie, activatie en retentie?",
    faq_a3: "Ik voer experimenteel gestuurde UI UX uit voor conversie-optimalisatie over aanmelding, onboarding en betaalmuur/afrekenen. Verwacht geprioriteerde A/B-tests en onboarding-optimalisatie om activatie te verhogen en churn te verminderen.",
    faq_q4: "Dekt u toegankelijkheid en prestaties?",
    faq_a4: "Ja - toegankelijkheid-eerste UI UX om te voldoen aan WCAG AA met semantische structuur, ARIA en toetsenbordstromen. Ik combineer dit met Core Web Vitals optimalisatie voor snelheid, SEO en betere mobiele conversie.",
    faq_q5: "Hoe werken prijs- en betrokkenheidsmodellen?",
    faq_a5: "Kies vaste-scope productized design pakketten, een maandelijks design abonnement, of een fractioneel product ontwerper model. Alle opties houden de snelheid hoog, kosten voorspelbaar, en roadmaps resultaatgericht.",
    faq_q6: "Met welke industrieën en regio's werkt u samen?",
    faq_a6: "Ik werk samen met SaaS, e-commerce, fintech, gezondheidszorg, onderwijs, en interne tools. Huur een remote UI UX ontwerper in voor wereldwijde teams met tijdzone-vriendelijke samenwerking in Europa, de VS, Canada, Singapore en Hong Kong.",
    pricing_label: "Prijzen",
    pricing_title: "Lidmaatschapsprijzen",
    pricing_italic: "prijzen",
    pricing_desc: "Investeer in design dat uw bedrijf aandrijft.<br>Duidelijke, rechttoe rechtaan plannen op maat van uw behoeften.",
    pricing_standard: "Standaard",
    pricing_standard_sub: "Transformeer uw bestaande ontwerp in een conversiemachine.",
    pricing_standard_price: "$849",
    pricing_standard_note: "Eenmalig. 50% vooruit, 50% bij levering",
    pricing_standard_btn: "Abonneer je vandaag nog",
    pricing_standard_link: "Boek een gesprek",
    pricing_standard_f1: "Compleet UX-audit met actiegerichte inzichten",
    pricing_standard_f2: "Strategische herontwerp van uw bestaande interface",
    pricing_standard_f3: "Figma-bestanden met ontwikkelaar-klaar specificaties",
    pricing_standard_f4: "2-3 dagen levering per aanvraag",
    pricing_standard_f5: "Tot 2 revisies per project",
    pricing_standard_f6: "Slack/Trello projectmanagement",
    pricing_standard_f7: "Pauzeer of annuleer op elk moment",
    pricing_standard_s1: "SaaS",
    pricing_standard_s2: "Herontwerp",
    pricing_standard_s3: "Optimalisatie",
    pricing_pro: "Pro",
    pricing_popular: "Populair",
    pricing_pro_sub: "Bouw uw merk vanaf de grond op met samenhangend, schaalbaar ontwerp.",
    pricing_pro_price: "$1,449",
    pricing_pro_note: "Eenmalig. 50% vooruit, 50% bij levering",
    pricing_pro_btn: "Abonneer je vandaag nog",
    pricing_pro_link: "Boek een gesprek",
    pricing_pro_f1: "Compleet merkidentiteitsontwikkeling",
    pricing_pro_f2: "Uitgebreide ontwerpsysteem creatie",
    pricing_pro_f3: "UI/UX ontwerp voor web en mobiel",
    pricing_pro_f4: "Tot 4 revisies per project",
    pricing_pro_f5: "Prioriteit 2-3 dagen doorlooptijd",
    pricing_pro_f6: "Geavanceerde prototyping en gebruikersstromen",
    pricing_pro_f7: "Merk richtlijnen documentatie",
    pricing_pro_s1: "Schaalbaarheid",
    pricing_pro_s2: "Opvallen",
    pricing_pro_s3: "Branding",
    pricing_project: "Projectgebaseerd",
    pricing_project_sub: "Aangepast ontwerp en ontwikkeling voor uw unieke visie.",
    pricing_project_price: "vanaf $2,499",
    pricing_project_note: "Eenmalig. 50% vooruit, 50% bij levering",
    pricing_project_btn: "Vraag een offerte aan",
    pricing_project_link: "Boek een gesprek",
    pricing_project_f1: "Aangepaste projectomvang en tijdlijn",
    pricing_project_f2: "Compleet merk en UI/UX ontwerp",
    pricing_project_f3: "Frontend ontwikkeling en implementatie",
    pricing_project_f4: "Responsieve, prestatie-geoptimaliseerde code",
    pricing_project_f5: "Onbeperkte revisies tijdens de ontwikkeling",
    pricing_project_f6: "Kwaliteitsborging en testen",
    pricing_project_f7: "3 maanden ondersteuning na de lancering",
    pricing_project_s1: "Ontwerpen",
    pricing_project_s2: "Ontwikkeling",
    pricing_project_s3: "Lancering",
    costs: "kost je meer dan je denkt",
    work: "Werk"
  },
  ar: {
  caseTitle: "توسيع شحن السيارات الكهربائية عالميًا",
  caseBannerAlt: "تطبيق شحن السيارات الكهربائية",
  roleLabel: "دوري:",
  role: "مصمم واجهات وتجربة مستخدم رئيسي",
  failedTitle: "ما الذي فشل؟",
  barrierTitle: "العائق",
  barrierDesc: "بدأت Sintio صغيرة، كصديق شحن في الحي. مفيدة، لكنها عالقة. لم تستطع المنصة التوسع، وكان التصميم غير عملي، والمستخدمون محبطون. تعثر المستخدمون في جلسات الشحن. لعن المشغلون الإدارة الفوضوية. التوسع لأوروبا أو أمريكا؟ مستحيل.",
  barrierHighlight: "لم تستطع المنصة التوسع، وكان التصميم غير عملي،",
  ibmTitle: "تفكير IBM المؤسسي",
  ibmDesc: "لكسر الجمود، اعتمدت على تفكير التصميم المؤسسي من IBM. لأنه يوازن بين قيود العمل واحتياجات المستخدمين الحقيقيين.",
  ibmImgAlt: "تصميم IBM المؤسسي",
  visionTitle: "تحديد الرؤية",
  visionDesc: "حددت نقطتين أساسيتين:",
  hillScalability: "قابلية التوسع: تمكين Sintio لتصبح حلاً للسيارات الكهربائية للشركات.",
  hillInvestor: "ثقة المستثمرين: إعادة تصميم تجربة واضحة وحديثة وقابلة للتمويل.",
  hillSummary: "هذه النقاط كانت الدليل لكل قرارات التصميم.",
  userFeedbackTitle: "ملاحظات المستخدمين الأولية (البوابة القديمة)",
  userFeedbackDesc: "في البداية، راقبت مستخدمين حقيقيين في البوابة.",
  userFeedbackPain: "نقاط الألم: تنقل مربك، قلة المرونة، ضعف الاستخدام.",
  userFeedbackBudget: "هذه كانت المشاكل الأساسية قبل قيود الميزانية.",
  sponsorTitle: "المستخدمون الرعاة — أصحاب المصلحة والمستثمرون",
  sponsorDesc: "في البداية، راقبت مستخدمين حقيقيين في البوابة.",
  sponsorPain: "نقاط الألم: تنقل مربك، قلة المرونة، ضعف الاستخدام.",
  sponsorBudget: "هذه كانت المشاكل الأساسية قبل قيود الميزانية.",
  playbacksTitle: "جلسات التكرار — التعاون التدريجي",
  playbacksDesc: "يركز IBM EDT على جلسات التكرار: نقاط مراجعة منتظمة.",
  playbacksSessions: "جلسات مراجعة عند كل مرحلة تصميم.",
  playbacksPrototypes: "نماذج Figma تم اختبارها وتحسينها جماعيًا.",
  playbacksSummary: "حافظ ذلك على شفافية التصميم وتعاونه.",
  iterationTitle: "التكرار ونظام التصميم",
  iterationDesc: "نظام تصميم قابل للتوسع للاتساق وقابلية العلامة البيضاء.",
  iterationFlows: "تكرار تدفقات الشحن والدفع وإدارة الأسطول.",
  iterationCycles: "كل دورة سهلت رحلة المستخدم وحققت أهداف العمل.",
  iterationSummary: "التفكير المنظومي ضمن الاستدامة.",
  reintroduceTitle: "إعادة إدخال المستخدمين الحقيقيين",
  reintroduceDesc: "بعد التمويل، أعدت المستخدمين الحقيقيين للعملية.",
  reintroduceInterviews: "مقابلات سياقية مع سائقي ومشغلي السيارات الكهربائية.",
  reintroduceObserve: "مراقبة التنقل في النماذج الجديدة مقابل القديمة.",
  reintroduceRefine: "التعديلات النهائية لضمان قابلية الاستخدام الحقيقية.",
  reintroduceSummary: "جسر بين التكرار المدفوع من أصحاب المصلحة والتحقق من المستخدمين.",
  reflectionTitle: "انعكاس",
  reflectionDesc1: "علمتني هذه التجربة أهمية التكيف مع الواقع. أعطاني تفكير IBM المؤسسي الهيكل لموازنة العمل والمستخدمين والرعاة. في النهاية، كان التصميم قابلًا للتمويل وقابلًا للاستخدام — حتى تحت الضغط، يمكن أن تحقق تجربة المستخدم تأثيرًا.",
  reflectionDesc2: "قادني إعادة تصميم Sintio كمصمم منفرد إلى دمج الاستراتيجية والتفكير التصميمي والتنفيذ بسلاسة. لم أكن أصمم شاشات فقط — بل كنت أوحد أصحاب المصلحة، وأشكل رؤية المنتج، وأمكّن جولة تمويل بقيمة $2M من خلال التصميم فقط. هذا ما أقدمه لأي فريق: وضوح، تكيف، وتأثير ملموس.",
    home: "الرئيسية",
    about: "عنّي",
    contact: "اتصل بي",
    copyright: "© كود من إيشان",
    ev: "منصة السيارات الكهربائية",
    hero_title: "تحويل المنتجات \u201dالعادية\u201d إلى رواد السوق",
    hero_para: "يهجر المستخدمون المنتجات المربكة في ثوانٍ. اجعل منتجك لا يُقاوم — استعن بمصمم واجهات وتجربة مستخدم يركز على الوصول (WCAG).",
    explore_btn: "استكشف عملي",
    explore_btn_text: "استكشف عملي",
    hero_sub: "تصميم تجارب إنسانية بديهية داخل أنظمة معقدة.",
    badge_product: "تصميم المنتج",
    badge_ux: "هندسة الواجهة",
    badge_ui: "استراتيجية تجربة المستخدم",
    badge_design: "أنظمة التصميم",
    meh: "عادي",
    problem_stat: "88٪ من المستخدمين يهجرون المنتجات بسبب تجربة المستخدم السيئة — واجهة المستخدم السيئة تحول القادة المحتملين إلى فشل منسي.",
    solution_title: "هكذا أجعل المنتجات تفوز",
    carousel_prev: "←",
    carousel_next: "→",
    story_title: "القصة أولاً",
    story_desc: "أصمم تفاعلات تركز على القصة لتوجيه الأشخاص بسلاسة عبر المنتج والويب والجوال—بناء صدى عاطفي يدوم بعد الجلسة. من رسم الرحلة إلى الأنظمة، يصبح صوت علامتك ملموسًا. اجعل منتجك لا يُنسى وجاهزًا للتحويل — استعن بمصمم تجربة العلامة التجارية للمنتجات متعددة المنصات.",
    conversion_title: "التركيز على التحويل",
    conversion_desc: "أصمم لتحقيق النتائج، وليس الجماليات—اختر خدمة تصميم واجهة وتجربة مستخدم تركز على التحويل لرفع الاشتراكات والإيرادات، مع كل قرار يقاس بمقاييس واضحة.",
    endtoend_title: "تنفيذ شامل",
    endtoend_desc: "من البحث والاستراتيجية إلى التصميم والتطوير والاختبار، أدير دورة المنتج كاملة لتحقيق النمو—خدمة تصميم وتطوير واجهة وتجربة مستخدم شاملة تركز على التحويل والاحتفاظ والتأثير القابل للقياس.",
    know_about: "اعرف عني →",
    testimonial_label: "توصية العميل",
    testimonial_title: "ماذا يقولون؟",
    testimonial_1: "لم يساعدني BNP فقط في كتابة كتاب—بل ساعدوني في إيجاد صوتي. لم أشعر بهذا القدر من الثقة من قبل.",
    testimonial_1_name: "نهى د.",
    testimonial_1_role: "مدربة صحة",
    testimonial_2: "من ملاحظات مبعثرة إلى كتاب مكتوب باحتراف في 30 يومًا. جعل الفريق العملية سلسة وحادة وخالية من التوتر",
    testimonial_2_name: "جاي ك.",
    testimonial_2_role: "مؤسس شركة ناشئة",
    testimonial_3: "لم أتخيل أبدًا أن أرى قصتي في كتاب—ولا أن أشعر بالفخر بها. كنت مرتبكًا، غير واثق، ولا أعرف من أين أبدأ. لكن British Noble Press استمعوا لي حقًا وحولوا ملاحظاتي إلى شيء قوي وشخصي.",
    testimonial_3_name: "فاطمة س.",
    testimonial_3_role: "استشارية أعمال، الإمارات",
    faq_title: "الأسئلة الشائعة",
    faq_q1: "ماذا تقدم بالضبط من البداية للنهاية؟",
    faq_a1: "أقدم خدمة شاملة للبحث والتصميم والتطوير والاختبار من الاكتشاف إلى الإطلاق. استعن بمصمم واجهة وتجربة مستخدم يبعد لإصدار قابل للقياس.",
    faq_q2: "هل يمكنك مساعدتنا في الإطلاق السريع من Figma؟",
    faq_a2: "نعم—تنفيذ جاهز للإطلاق من Figma إلى Webflow أو Framer بدقة بكسل، ونظام إدارة محتوى وتحليلات. احجز بناء يركز على التحويل ويشحن بسرعة للفرق العالمية.",
    faq_q3: "كيف تحسن التحويل والتفعيل والاحتفاظ؟",
    faq_a3: "أدير تجارب واجهة وتجربة مستخدم لتحسين التحويل عبر التسجيل والتفعيل والدفع. توقع اختبارات A/B وتحسينات لرفع التفعيل وتقليل التسرب.",
    faq_q4: "هل تغطي الوصول والأداء؟",
    faq_a4: "نعم—تصميم يركز على الوصول لتلبية WCAG AA مع بنية دلالية وتدفقات لوحة المفاتيح. أدمج ذلك مع تحسين الأداء للسرعة والسيو وتحويل أفضل على الجوال.",
    faq_q5: "كيف تعمل نماذج التسعير والتعاقد؟",
    faq_a5: "اختر باقات تصميم محددة النطاق أو اشتراك شهري أو نموذج مصمم جزئي. جميع الخيارات تحافظ على السرعة والتكلفة والنتائج.",
    faq_q6: "ما الصناعات والمناطق التي تعمل معها؟",
    faq_a6: "أتعاون مع SaaS، التجارة الإلكترونية، التكنولوجيا المالية، الصحة، التعليم، والأدوات الداخلية. استعن بمصمم واجهة وتجربة مستخدم يبعد للفرق العالمية.",
    pricing_label: "التسعير",
    pricing_title: "تسعير العضوية",
    pricing_italic: "التسعير",
    pricing_desc: "استثمر في التصميم الذي يدفع عملك للأمام.<br>خطط واضحة ومباشرة تناسب احتياجاتك.",
    pricing_standard: "قياسي",
    pricing_standard_sub: "حوّل تصميمك الحالي إلى آلة تحويل.",
    pricing_standard_price: "$849",
    pricing_standard_note: "دفعة واحدة. 50٪ مقدّم، 50٪ عند التسليم",
    pricing_standard_btn: "اشترك اليوم",
    pricing_standard_link: "احجز مكالمة",
    pricing_standard_f1: "تدقيق UX كامل مع رؤى قابلة للتنفيذ",
    pricing_standard_f2: "إعادة تصميم استراتيجية لواجهتك الحالية",
    pricing_standard_f3: "ملفات Figma بمواصفات جاهزة للمطور",
    pricing_standard_f4: "تسليم خلال 2-3 أيام لكل طلب",
    pricing_standard_f5: "حتى 2 مراجعة لكل مشروع",
    pricing_standard_f6: "إدارة المشروع عبر Slack/Trello",
    pricing_standard_f7: "إيقاف أو إلغاء في أي وقت",
    pricing_standard_s1: "SaaS",
    pricing_standard_s2: "إعادة تصميم",
    pricing_standard_s3: "تحسين",
    pricing_pro: "احترافي",
    pricing_popular: "شائع",
    pricing_pro_sub: "ابنِ علامتك التجارية من الصفر بتصميم متماسك وقابل للتوسع.",
    pricing_pro_price: "$1,449",
    pricing_pro_note: "دفعة واحدة. 50٪ مقدّم، 50٪ عند التسليم",
    pricing_pro_btn: "اشترك اليوم",
    pricing_pro_link: "احجز مكالمة",
    pricing_pro_f1: "تطوير هوية العلامة التجارية بالكامل",
    pricing_pro_f2: "إنشاء نظام تصميم شامل",
    pricing_pro_f3: "تصميم واجهة وتجربة مستخدم للويب والجوال",
    pricing_pro_f4: "حتى 4 مراجعات لكل مشروع",
    pricing_pro_f5: "أولوية تسليم خلال 2-3 أيام",
    pricing_pro_f6: "نماذج أولية متقدمة وتدفقات المستخدم",
    pricing_pro_f7: "توثيق إرشادات العلامة التجارية",
    pricing_pro_s1: "توسيع",
    pricing_pro_s2: "تميّز",
    pricing_pro_s3: "العلامة التجارية",
    pricing_project: "حسب المشروع",
    pricing_project_sub: "تصميم وتطوير مخصص لرؤيتك الفريدة.",
    pricing_project_price: "من $2,499",
    pricing_project_note: "دفعة واحدة. 50٪ مقدّم، 50٪ عند التسليم",
    pricing_project_btn: "طلب عرض سعر",
    pricing_project_link: "احجز مكالمة",
    pricing_project_f1: "نطاق وتوقيت مشروع مخصص",
    pricing_project_f2: "تصميم واجهة وتجربة مستخدم وهوية كاملة",
    pricing_project_f3: "تطوير وتنفيذ الواجهة الأمامية",
    pricing_project_f4: "كود سريع ومحسّن للأداء",
    pricing_project_f5: "مراجعات غير محدودة أثناء التطوير",
    pricing_project_f6: "ضمان الجودة والاختبار",
    pricing_project_f7: "دعم بعد الإطلاق لمدة 3 أشهر",
    pricing_project_s1: "تصميم",
    pricing_project_s2: "تطوير",
    pricing_project_s3: "إطلاق",
    costs: "يكلفك أكثر مما تعتقد",
    work: "العمل"
  },
  zh: {
  caseTitle: "全球扩展电动汽车充电",
  caseBannerAlt: "电动汽车充电应用",
  roleLabel: "我的角色：",
  role: "首席 UI UX 设计师",
  failedTitle: "失败了什么？",
  barrierTitle: "障碍",
  barrierDesc: "Sintio 起步小，像邻里充电伙伴。可爱、实用……但受限。平台无法扩展，设计笨拙，用户叹气多于微笑。充电过程混乱，运营者抱怨管理。扩展到欧洲或美国？没戏。",
  barrierHighlight: "平台无法扩展，设计笨拙，",
  ibmTitle: "IBM 企业思维",
  ibmDesc: "为打破僵局，我采用了 IBM 企业设计思维。它让我平衡业务约束和真实用户需求。",
  ibmImgAlt: "IBM 企业设计",
  visionTitle: "设定愿景",
  visionDesc: "我定义了两个核心目标：",
  hillScalability: "可扩展性：让 Sintio 成为企业的白标 EV 解决方案。",
  hillInvestor: "投资者信心：重新设计体验，清晰、现代、可融资。",
  hillSummary: "这些目标指引所有设计决策。",
  userFeedbackTitle: "初始用户反馈（旧门户）",
  userFeedbackDesc: "一开始，我观察了真实用户使用旧门户。",
  userFeedbackPain: "痛点：导航混乱、灵活性差、可用性低。",
  userFeedbackBudget: "这些是预算限制前的基础问题。",
  sponsorTitle: "赞助用户 — 利益相关者与投资者",
  sponsorDesc: "一开始，我观察了真实用户使用旧门户。",
  sponsorPain: "痛点：导航混乱、灵活性差、可用性低。",
  sponsorBudget: "这些是预算限制前的基础问题。",
  playbacksTitle: "回放 — 迭代协作",
  playbacksDesc: "IBM EDT 强调回放：定期对齐检查点。",
  playbacksSessions: "每个设计里程碑都进行回放。",
  playbacksPrototypes: "Figma 原型经过测试、批评和协作改进。",
  playbacksSummary: "保持设计透明、迭代和协作。",
  iterationTitle: "迭代与设计系统",
  iterationDesc: "开发可扩展的设计系统，实现一致性和白标适应性。",
  iterationFlows: "迭代充电、支付和车队管理流程。",
  iterationCycles: "每轮简化用户旅程并实现业务目标。",
  iterationSummary: "系统思维确保长期可扩展性。",
  reintroduceTitle: "重新引入真实用户",
  reintroduceDesc: "获得资金后，我重新引入了真实用户。",
  reintroduceInterviews: "与 EV 司机和运营者进行情境访谈。",
  reintroduceObserve: "观察他们在新原型与旧门户的导航。",
  reintroduceRefine: "最终调整确保设计满足真实可用性标准。",
  reintroduceSummary: "弥合了利益相关者驱动迭代与用户验证设计的差距。",
  reflectionTitle: "反思",
  reflectionDesc1: "这个项目让我认识到适应现实的重要性。IBM 企业设计思维让我平衡业务、赞助方和用户验证。最终，设计不仅可融资，还可用——即使在压力下，UX 思维也能带来商业和人本价值。",
  reflectionDesc2: "作为独立设计师领导 Sintio 的重塑，让我将战略、设计思维和执行融为一体。我不仅在做界面，更在统一利益相关者、塑造产品愿景，并通过设计促成 $2M 融资。这就是我能为团队带来的：清晰、适应性和可衡量的影响。",
    home: "首页",
    about: "关于我",
    contact: "联系我",
    copyright: "© Ishan 编写的代码",
    ev: "电动汽车平台",
    hero_title: "将“平庸”产品变为市场领导者",
    hero_para: "用户会在几秒钟内放弃令人困惑的产品。让你的产品无法忽视——聘请专注于无障碍的 UI UX 设计师 (WCAG)。",
    explore_btn: "探索我的作品",
    explore_btn_text: "探索我的作品",
    hero_sub: "在复杂系统中打造直观、以人为本的体验。",
    badge_product: "产品设计",
    badge_ux: "界面工程",
    badge_ui: "用户体验策略",
    badge_design: "设计系统",
    meh: "平庸",
    problem_stat: "88% 的用户因糟糕的用户体验而放弃产品——糟糕的 UI UX 让潜在的市场领导者变成被遗忘的失败者。",
    solution_title: "我让产品获胜的方法",
    carousel_prev: "←",
    carousel_next: "→",
    story_title: "故事为先",
    story_desc: "我设计以故事为核心的互动，引导用户轻松跨越产品、网页和移动端——建立持久的情感共鸣。从旅程映射到组件系统，你的品牌声音变得具体。让你的产品令人难忘并具备转化力——聘请跨平台品牌体验设计师。",
    conversion_title: "转化为核心",
    conversion_desc: "我以结果为导向设计——选择以转化为核心的 UI UX 设计服务，提升注册、激活和收入，每个决策都以明确的漏斗指标衡量。",
    endtoend_title: "端到端执行",
    endtoend_desc: "从研究和策略到设计、开发和测试，我全程参与产品周期，推动增长——专注于转化、留存和可衡量影响的端到端 UI UX 设计与开发服务。",
    know_about: "了解我 →",
    testimonial_label: "客户评价",
    testimonial_title: "他们怎么说？",
    testimonial_1: "BNP 不仅帮我写了书——还帮我找到了自己的声音。我从未如此自信。",
    testimonial_1_name: "Neha D.",
    testimonial_1_role: "健康教练",
    testimonial_2: "从零散笔记到 30 天内专业成书。团队让整个过程顺畅、专业、无压力",
    testimonial_2_name: "Jay K.",
    testimonial_2_role: "初创公司创始人",
    testimonial_3: "我从未想过能看到自己的故事成书——更没想到会为之自豪。曾经迷茫、不知所措，但 British Noble Press 真正倾听了我，把我的语音笔记变成了有力且个性化的作品。",
    testimonial_3_name: "Fatima S.",
    testimonial_3_role: "商业顾问，阿联酋",
    faq_title: "常见问题",
    faq_q1: "你到底能交付什么？",
    faq_a1: "我提供端到端的 UI UX 研究、设计、前端开发和测试服务，从发现到上线。聘请远程 UI UX 设计师和前端开发者，确保可衡量的发布。",
    faq_q2: "你能帮我们从 Figma 快速上线吗？",
    faq_a2: "可以——像素级 Figma 到 Webflow 或 Framer 实现，配备 CMS 和分析。预订以转化为核心、快速交付的构建服务，适合全球团队。",
    faq_q3: "你如何提升转化、激活和留存？",
    faq_a3: "我通过实验驱动的 UI UX 优化注册、引导和付费流程。优先进行 A/B 测试和引导优化，提高激活率，减少流失。",
    faq_q4: "你覆盖无障碍和性能吗？",
    faq_a4: "是的——以无障碍为核心的 UI UX，满足 WCAG AA，采用语义结构、ARIA 和键盘流程。结合核心 Web Vitals 优化速度、SEO 和移动端转化。",
    faq_q5: "定价和合作模式如何？",
    faq_a5: "选择固定范围的产品化设计包、月度设计订阅或部分产品设计师模式。所有选项都保证高速度、可预测成本和以结果为导向的路线图。",
    faq_q6: "你服务哪些行业和地区？",
    faq_a6: "我与 SaaS、电商、金融科技、医疗、教育和内部工具合作。聘请远程 UI UX 设计师，全球团队时区友好协作。",
    pricing_label: "价格",
    pricing_title: "会员价格",
    pricing_italic: "价格",
    pricing_desc: "投资于推动业务发展的设计。<br>清晰、直接的方案，量身定制。",
    pricing_standard: "标准版",
    pricing_standard_sub: "将现有设计转变为转化机器。",
    pricing_standard_price: "$849",
    pricing_standard_note: "一次性。50% 预付，50% 交付时",
       pricing_standard_btn: "立即订阅",
    pricing_standard_link: "预约通话",
    pricing_standard_f1: "完整 UX 审核，提供可执行见解",
    pricing_standard_f2: "现有界面的战略性重设计",
    pricing_standard_f3: "Figma 文件，开发者可用规范",
    pricing_standard_f4: "每个请求 2-3 天交付",
    pricing_standard_f5: "每个项目最多 2 次修订",
    pricing_standard_f6: "Slack/Trello 项目管理",
    pricing_standard_f7: "随时暂停或取消",
    pricing_standard_s1: "SaaS",
    pricing_standard_s2: "重设计",
    pricing_standard_s3: "优化",
    pricing_pro: "专业版",
    pricing_popular: "热门",
    pricing_pro_sub: "从零打造品牌，设计统一且可扩展。",
    pricing_pro_price: "$1,449",
    pricing_pro_note: "一次性。50% 预付，50% 交付时",
    pricing_pro_btn: "立即订阅",
    pricing_pro_link: "预约通话",
    pricing_pro_f1: "完整品牌识别开发",
    pricing_pro_f2: "全面设计系统创建",
    pricing_pro_f3: "网页和移动端 UI/UX 设计",
    pricing_pro_f4: "每个项目最多 4 次修订",
    pricing_pro_f5: "优先 2-3 天交付",
    pricing_pro_f6: "高级原型和用户流程",
    pricing_pro_f7: "品牌指南文档",
    pricing_pro_s1: "扩展",
    pricing_pro_s2: "脱颖而出",
    pricing_pro_s3: "品牌",
    pricing_project: "项目制",
    pricing_project_sub: "为您的独特愿景定制设计与开发。",
    pricing_project_price: "起价 $2,499",
    pricing_project_note: "一次性。50% 预付，50% 交付时",
    pricing_project_btn: "请求报价",
    pricing_project_link: "预约通话",
    pricing_project_f1: "定制项目范围和时间表",
    pricing_project_f2: "完整品牌和 UI/UX 设计",
    pricing_project_f3: "前端开发与实现",
    pricing_project_f4: "响应式、性能优化代码",
    pricing_project_f5: "开发期间无限修订",
    pricing_project_f6: "质量保证与测试",
    pricing_project_f7: "上线后 3 个月支持",
    pricing_project_s1: "设计",
    pricing_project_s2: "开发",
    pricing_project_s3: "上线",
    costs: "成本超乎你的想象",
    work: "作品"
  },
  es: {
  caseTitle: "Escalando la carga EV globalmente",
  caseBannerAlt: "App de carga EV",
  roleLabel: "Mi rol:",
  role: "Lead UI UX Designer",
  failedTitle: "¿Qué falló?",
  barrierTitle: "La barrera",
  barrierDesc: "Sintio comenzó pequeño, como un compañero de carga del vecindario. Útil, pero estancado. La plataforma no podía escalar, el diseño era torpe y los usuarios suspiraban más de lo que sonreían. Los usuarios tropezaban en las sesiones de carga. Los operadores maldecían la gestión desordenada. ¿Escalar a Europa o EE.UU.? Olvídalo.",
  barrierHighlight: "La plataforma no podía escalar, el diseño era torpe,",
  ibmTitle: "Pensamiento empresarial IBM",
  ibmDesc: "Para romper el estancamiento, recurrí al Pensamiento de Diseño Empresarial de IBM. Porque me permitió equilibrar las restricciones comerciales con las necesidades reales de los usuarios.",
  ibmImgAlt: "Diseño empresarial IBM",
  visionTitle: "Estableciendo la visión",
  visionDesc: "Definí dos “Hills” principales:",
  hillScalability: "Escalabilidad: Permitir que Sintio sea una solución EV de marca blanca para empresas.",
  hillInvestor: "Confianza del inversor: Rediseñar la experiencia para que sea clara, moderna, y financiable.",
  hillSummary: "Estas Hills guiaron todas las decisiones de diseño.",
  userFeedbackTitle: "Feedback inicial de usuarios (Portal antiguo)",
  userFeedbackDesc: "Al principio, observé a usuarios reales usando el portal existente.",
  userFeedbackPain: "Puntos de dolor: navegación confusa, falta de flexibilidad y mala usabilidad.",
  userFeedbackBudget: "Esto me dio los problemas base antes de las restricciones presupuestarias.",
  sponsorTitle: "Usuarios patrocinadores — Stakeholders & inversores",
  sponsorDesc: "Al principio, observé a usuarios reales usando el portal existente.",
  sponsorPain: "Puntos de dolor: navegación confusa, falta de flexibilidad y mala usabilidad.",
  sponsorBudget: "Esto me dio los problemas base antes de las restricciones presupuestarias.",
  playbacksTitle: "Playbacks — Colaboración iterativa",
  playbacksDesc: "IBM EDT enfatiza los Playbacks: puntos de control regulares.",
  playbacksSessions: "Realicé sesiones de playback en cada hito de diseño.",
  playbacksPrototypes: "Prototipos en Figma probados, criticados y mejorados colaborativamente.",
  playbacksSummary: "Esto mantuvo el diseño transparente, iterativo y colaborativo.",
  iterationTitle: "Iteración y sistema de diseño",
  iterationDesc: "Desarrollé un sistema de diseño escalable para consistencia y adaptabilidad de marca blanca.",
  iterationFlows: "Iteré en flujos de carga, pagos y gestión de flotas.",
  iterationCycles: "Cada ciclo simplificó los recorridos de usuario y cumplió objetivos comerciales.",
  iterationSummary: "El pensamiento sistémico aseguró la escalabilidad a largo plazo.",
  reintroduceTitle: "Reintroduciendo usuarios reales",
  reintroduceDesc: "Una vez asegurada la financiación, reintroduje usuarios reales en el proceso.",
  reintroduceInterviews: "Entrevistas contextuales con conductores y operadores EV.",
  reintroduceObserve: "Los observé navegando los prototipos rediseñados vs. el portal antiguo.",
  reintroduceRefine: "Se hicieron ajustes finales para asegurar la usabilidad real.",
  reintroduceSummary: "Esto cerró la brecha entre iteraciones impulsadas por stakeholders y diseño validado por usuarios.",
  reflectionTitle: "Reflexión",
  reflectionDesc1: "Este proyecto me enseñó la importancia de adaptar los métodos de diseño a la realidad. El Pensamiento de Diseño Empresarial de IBM me dio la estructura para equilibrar restricciones comerciales, aportes de patrocinadores y validación real de usuarios. Al final, el diseño fue financiable y usable — incluso bajo presión, el pensamiento UX puede aportar impacto comercial y valor humano.",
  reflectionDesc2: "Liderar la renovación de Sintio como diseñador único me enseñó a fusionar estrategia, pensamiento de diseño y ejecución en un solo proceso. No solo creaba pantallas — alineaba stakeholders, definía la visión del producto y habilitaba una ronda de financiación de $2M solo con diseño. Este caso refleja lo que aporto a cualquier equipo: claridad, adaptabilidad e impacto medible.",
    home: "Inicio",
    about: "Sobre mí",
    contact: "Contáctame",
    copyright: "© Código por Ishan",
    ev: "Plataforma EV",
    hero_title: "Convirtiendo productos \u201dmeh\u201d en líderes del mercado",
    hero_para: "Los usuarios abandonan productos confusos en segundos. Haz que el tuyo sea imposible de ignorar — contrata un diseñador UI UX enfocado en accesibilidad (WCAG).",
    explore_btn: "Explora mi trabajo",
    explore_btn_text: "Explora mi trabajo",
    hero_sub: "Creando experiencias intuitivas y humanas dentro de sistemas complejos.",
    badge_product: "Diseño de producto",
    badge_ux: "Ingeniería UI",
    badge_ui: "Estrategia UX",
    badge_design: "Sistemas de diseño",
    meh: "Meh",
    problem_stat: "El 88% de los usuarios abandonan productos por mala experiencia — una mala UI UX convierte líderes potenciales en fracasos olvidados.",
    solution_title: "Así hago que los productos ganen",
    carousel_prev: "←",
    carousel_next: "→",
    story_title: "PRIMERO LA HISTORIA",
    story_desc: "Diseño interacciones centradas en la historia que guían a las personas por producto, web y móvil—creando resonancia emocional que dura más allá de la sesión. Desde mapeo de viajes y microcopy hasta sistemas de componentes, tu voz de marca se vuelve tangible. Haz tu producto memorable y listo para convertir — contrata un diseñador de experiencia de marca para productos multiplataforma.",
    conversion_title: "ENFOQUE EN CONVERSIÓN",
    conversion_desc: "Diseño para resultados, no estética—elige un servicio UI UX enfocado en conversión para aumentar registros, activación e ingresos, con cada decisión medida por métricas claras.",
    endtoend_title: "EJECUCIÓN DE PRINCIPIO A FIN",
    endtoend_desc: "Desde investigación y estrategia hasta diseño, desarrollo y pruebas, gestiono el ciclo completo para impulsar el crecimiento—servicio UI UX integral enfocado en conversión, retención e impacto medible.",
    know_about: "Conóceme →",
    testimonial_label: "Testimonio del cliente",
    testimonial_title: "¿Qué dicen?",
    testimonial_1: "BNP no solo me ayudó a escribir un libro—me ayudaron a encontrar mi voz. Nunca me he sentido tan seguro de mi historia.",
    testimonial_1_name: "Neha D.",
    testimonial_1_role: "Coach de bienestar",
    testimonial_2: "De notas dispersas a un libro profesional en 30 días. El equipo hizo todo el proceso fluido, preciso y sin estrés",
    testimonial_2_name: "Jay K.",
    testimonial_2_role: "Fundador de startup",
    testimonial_3: "Nunca imaginé ver mi historia en un libro—let alone feel proud of it. I was overwhelmed, unsure, and had no idea where to begin. But British Noble Press listened to me, really listened, and turned my messy voice notes into something powerful and personal.",
    testimonial_3_name: "Fatima S.",
    testimonial_3_role: "Consultora de negocios, EAU",
    faq_title: "Preguntas frecuentes",
    faq_q1: "¿Qué entregas exactamente de principio a fin?",
    faq_a1: "Entrego un servicio integral de investigación, diseño, desarrollo front-end y pruebas UI UX desde el descubrimiento hasta el lanzamiento. Contrata un diseñador UI UX remoto y desarrollador front-end para un lanzamiento medible.",
    faq_q2: "¿Puedes ayudarnos a lanzar rápido desde Figma?",
    faq_a2: "Sí—implementación lista para lanzar de Figma a Webflow o Framer con precisión de píxeles, CMS y analítica. Reserva una construcción enfocada en conversión y entrega rápida para equipos globales.",
    faq_q3: "¿Cómo mejoras conversión, activación y retención?",
    faq_a3: "Gestiono UI UX orientado a experimentos para optimizar conversión en registro, onboarding y pago. Espera tests A/B y optimización de onboarding para aumentar activación y reducir abandono.",
    faq_q4: "¿Cubres accesibilidad y rendimiento?",
    faq_a4: "Sí—UI UX enfocado en accesibilidad para cumplir WCAG AA con estructura semántica, ARIA y flujos de teclado. Lo combino con optimización de Core Web Vitals para velocidad, SEO y mejor conversión móvil.",
    faq_q5: "¿Cómo funcionan los modelos de precios y contratación?",
    faq_a5: "Elige paquetes de diseño de alcance fijo, suscripción mensual o modelo de diseñador fraccional. Todas las opciones mantienen alta velocidad, costos predecibles y hojas de ruta orientadas a resultados.",
    faq_q6: "¿Con qué industrias y regiones trabajas?",
    faq_a6: "Trabajo con SaaS, e-commerce, fintech, salud, educación y herramientas internas. Contrata un diseñador UI UX remoto para equipos globales con colaboración amigable en zona horaria.",
    pricing_label: "Precios",
    pricing_title: "Precios de membresía",
    pricing_italic: "precios",
    pricing_desc: "Invierte en diseño que impulsa tu negocio.<br>Planes claros y directos adaptados a tus necesidades.",
    pricing_standard: "Estándar",
    pricing_standard_sub: "Transforma tu diseño actual en una máquina de conversión.",
    pricing_standard_price: "$849",
    pricing_standard_note: "Pago único. 50% anticipo, 50% en entrega",
    pricing_standard_btn: "Suscríbete hoy",
    pricing_standard_link: "Agenda una llamada",
    pricing_standard_f1: "Auditoría UX completa con insights accionables",
    pricing_standard_f2: "Rediseño estratégico de tu interfaz actual",
    pricing_standard_f3: "Archivos Figma con especificaciones para desarrollador",
    pricing_standard_f4: "Entrega de 2-3 días por solicitud",
    pricing_standard_f5: "Hasta 2 revisiones por proyecto",
    pricing_standard_f6: "Gestión de proyecto por Slack/Trello",
    pricing_standard_f7: "Pausa o cancela en cualquier momento",
    pricing_standard_s1: "SaaS",
    pricing_standard_s2: "Rediseño",
    pricing_standard_s3: "Optimización",
    pricing_pro: "Pro",
    pricing_popular: "Popular",
    pricing_pro_sub: "Construye tu marca desde cero con diseño cohesivo y escalable.",
    pricing_pro_price: "$1,449",
    pricing_pro_note: "Pago único. 50% anticipo, 50% en entrega",
    pricing_pro_btn: "Suscríbete hoy",
    pricing_pro_link: "Agenda una llamada",
    pricing_pro_f1: "Desarrollo completo de identidad de marca",
    pricing_pro_f2: "Creación de sistema de diseño integral",
    pricing_pro_f3: "Diseño UI/UX para web y móvil",
    pricing_pro_f4: "Hasta 4 revisiones por proyecto",
    pricing_pro_f5: "Entrega prioritaria de 2-3 días",
    pricing_pro_f6: "Prototipos avanzados y flujos de usuario",
    pricing_pro_f7: "Documentación de guías de marca",
    pricing_pro_s1: "Escalado",
    pricing_pro_s2: "Destacar",
    pricing_pro_s3: "Branding",
    pricing_project: "Por proyecto",
    pricing_project_sub: "Diseño y desarrollo personalizado para tu visión única.",
    pricing_project_price: "desde $2,499",
    pricing_project_note: "Pago único. 50% anticipo, 50% en entrega",
    pricing_project_btn: "Solicitar cotización",
    pricing_project_link: "Agenda una llamada",
    pricing_project_f1: "Alcance y cronograma de proyecto personalizado",
    pricing_project_f2: "Diseño completo de marca y UI/UX",
    pricing_project_f3: "Desarrollo e implementación front-end",
    pricing_project_f4: "Código optimizado y responsivo",
    pricing_project_f5: "Revisiones ilimitadas durante el desarrollo",
    pricing_project_f6: "Aseguramiento de calidad y pruebas",
    pricing_project_f7: "Soporte post-lanzamiento por 3 meses",
    pricing_project_s1: "Diseño",
    pricing_project_s2: "Desarrollo",
    pricing_project_s3: "Lanzamiento",
    costs: "cuesta más de lo que piensas",
    work: "Trabajo"
  }
};

function setLanguage(lang) {
    Object.keys(translations[lang]).forEach(function(key) {
        var elements = document.querySelectorAll('[data-i18n="' + key + '"]');
        elements.forEach(function(el) {
            if (key === 'meh') {
                // Do not change 'meh' at all
                // Leave its content and markup untouched
            } else {
                el.innerHTML = translations[lang][key];
            }
        });
    });
}

document.addEventListener('DOMContentLoaded', function() {
  const langSwitcher = document.getElementById('langSwitcher');
  if (langSwitcher) {
    langSwitcher.addEventListener('change', function() {
      setLanguage(this.value);
    });
    setLanguage(langSwitcher.value);
  }
});
